Revert hook modifications

diff --git a/gitlint-core/gitlint/files/commit-msg b/gitlint-core/gitlint/files/commit-msg
--- a/gitlint-core/gitlint/files/commit-msg
+++ b/gitlint-core/gitlint/files/commit-msg
@@ -1,16 +1,16 @@
 #!/bin/sh
 ### gitlint commit-msg hook start ###
 
-# # Determine whether we have a tty available by trying to access it.
-# # This allows us to deal with UI based gitclient's like Atlassian SourceTree.
-# # NOTE: "exec < /dev/tty" sets stdin to the keyboard
+# Determine whether we have a tty available by trying to access it.
+# This allows us to deal with UI based gitclient's like Atlassian SourceTree.
+# NOTE: "exec < /dev/tty" sets stdin to the keyboard
 stdin_available=1
 (exec < /dev/tty) 2> /dev/null || stdin_available=0
 
-echo "STDIN AVAILABLE: $stdin_available"
+# echo "STDIN AVAILABLE: $stdin_available"
 
 if [ $stdin_available -eq 1 ]; then
-    echo  "set stdin to tty"
+    # echo  "set stdin to tty"
     # Now that we know we have a functional tty, set stdin to it so we can ask the user questions :-)
     exec < /dev/tty
 
@@ -22,22 +22,22 @@ if [ $stdin_available -eq 1 ]; then
     # fi
 fi
 
-gitlint issue298
+# gitlint issue298
 
-echo -e "\033[31m TEST in red \033[0m"
+# echo -e "\033[31m TEST in red \033[0m"
 
 
-# gitlint --staged --msg-filename "$1" run-hook
-# exit_code=$?
+gitlint --staged --msg-filename "$1" run-hook
+exit_code=$?
 
-# # If we fail to find the gitlint binary (command not found), let's retry by executing as a python module.
-# # This is the case for Atlassian SourceTree, where $PATH deviates from the user's shell $PATH.
-# if [ $exit_code -eq 127 ]; then
-#     echo "Fallback to python module execution"
-#     python -m gitlint.cli --staged --msg-filename "$1" run-hook
-#     exit_code=$?
-# fi
+# If we fail to find the gitlint binary (command not found), let's retry by executing as a python module.
+# This is the case for Atlassian SourceTree, where $PATH deviates from the user's shell $PATH.
+if [ $exit_code -eq 127 ]; then
+    echo "Fallback to python module execution"
+    python -m gitlint.cli --staged --msg-filename "$1" run-hook
+    exit_code=$?
+fi
 
-# exit $exit_code
+exit $exit_code
 
-# ### gitlint commit-msg hook end ###
+### gitlint commit-msg hook end ###
