GHA: Alternative way to get PR number for notify
This will require a follow-up PR to get right.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -251,6 +251,21 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Check PR number
+        id: pr_check
+        run: |
+          if [[ -z "${{ github.event.pull_request.number }}" ]]; then
+            echo "::error::This workflow requires a pull request to be associated with the push event."
+            exit 1
+          fi
+
+      - name: Get PR number
+        id: pr
+        run: |
+          pr_number=${{ github.event.pull_request.number }}
+          echo "PR_NUMBER2=$pr_number" >> $GITHUB_ENV
+          echo "PR_NUMBER2=$pr_number"
+  
       - name: Get PR number
         run: |
           commit_sha=$(git rev-parse HEAD)
